### ISSUE TITLE
接口参数支持在线录入编辑，选取上个接口返回值么

### ISSUE THREAD

**Issue by 512433465** [shirleydl/ATest#3]

**Comment by shirleydl** [comment]
可以，在测试集用例管理里面添加用例后可以设置绑定变量，用${Content:xxx}函数获取返回值进行赋值，然后用例里面可以用${Bind:xxx}引用绑定变量

**Comment by 512433465** [comment]
感谢老铁的耐心指导。我仔细学习研究一下。
