### ISSUE TITLE
结果无法赋值给变量

### ISSUE THREAD

**Issue by 924408188** [shirleydl/ATest#5]
http返回值：{"code":0,"data":{"list":{"access_token":"shopping:login_user_5ab75c9fc7f8ecc64f2ddaf6335da6ef","user_id":"34645623434qwe","nickname":"oscar"}},"error_msg":""}
在用例中设置变量access_token=${Content:data}/${Content:list.access_token}，只能获取${Content:data}的返回值，${Content:data}/${Content:list.access_token}无法正常获取。在学习您的代码，修改GetValue类文件已解决上面的问题。但如果下个用例依赖上个登陆接口返回值token，如何设置，变量在新用例参数里如何表示｛access_token｝？期待你的回复谢谢。QQ：924408188

**Comment by shirleydl** [comment]
- access_token=${Content:data}/${Content:list.access_token}
这个写法错误，如果需要使用多个函数拼接值，需要使用连接符“&_&”,如：
```
${Content:data}&_&/&_&${Content:list.access_token}
```
- 下个用例依赖上个登陆接口返回值，如何设置?
1、使用测试集绑定变量（也可以叫：测试集变量）。如：用例A传值给用例B，在测试集里面先添加好关联用例A、B，然后设置用例A的绑定变量，设置变量名（如：s1）和变量值，然后用例B，可以是直接引用${Bind:s1}直接调用
2、使用前置任务（前置任务里面的所有测试集绑定变量可以贡献给当前执行的任务），可以把登录步骤单独放在一个测试集里，然后再任务管理里面，单独放在一个测试任务里（如：任务名A），每次其他测试任务需要使用登录步骤时，直接在任务设置里面，设置前置任务，既可以调用

详细可以看wiki，qq：3318549466
